name: aws_bedrock_sdk
description: AWS Bedrock SDK
version: 1.0.1
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:

  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_aws_api: ^2.0.0
  uuid: ^4.5.1
  xml: ^6.5.0

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  build_runner: any
  dotenv: ^4.2.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: any
  test: any
